### PR TITLE
Likelihood function corrected

### PR DESCRIPTION
**Pull request by csparker**
Sequence likelihood calculation in mcmc() now corrected to match Fonteijn 2012.
Updated files: get_prob_mat(), probability() (gmm and kde classes) and pdf() (gmm and kde classes).

### CODE REVIEW

**Comment by sea-shunned** [comment]
Thanks Chris!

I just have one question:
With the mixture weights removed in the `pdf()` function for the 2 MM classes, doesn't this need to be added back in when calculating the likelihood (i.e. [here](https://github.com/csparker/kde_ebm/blob/b2b1b7b79c4dd7bd4748b3385da5a84d3e6d6b08/kde_ebm/mixture_model/gmm.py#L95))?

**Comment by csparker** [comment]
Hi Cameron, 

Just to be clear, the likelihood function I corrected is for the probability of the data given the sequence (Fonteijn 2021 equation 4). It looks like the likelihood() you link to is being used to fit the mixture model components (weights and pdfs). The pdf's (not the weights) from these are needed to compute the likelihood of the sequence. 

So yes for the mixture model fitting the weights would need to be included in likelihood(), I think like this: p(x|MM) = cn_pdf * weight_cn + ad_pdf * (1-weight_ad). This should not affect the computation of the sequence likelihood though, which is computed in the mcmc() function via get_prob_mat().

**Review by sea-shunned — CHANGES_REQUESTED** [review]
With the changes to the `probability()` function, the call to this in the [`plotting.mixture_model_grid()`](https://github.com/csparker/kde_ebm/blob/master/kde_ebm/plotting/plotting.py#L61) function needs updating, which (to keep it the same as it was before) would be:

```python
probability = 1-(controls_score / (controls_score+patholog_score))
probability *= np.max((patholog_score, controls_score))
```

**Comment by sea-shunned** [comment]
> So yes for the mixture model fitting the weights would need to be included in likelihood(), I think like this: p(x|MM) = cn_pdf * weight_cn + ad_pdf * (1-weight_cn). This should not affect the computation of the sequence likelihood though, which is computed in the mcmc() function via get_prob_mat().

Agreed! It's just the likelihood function for the MM, not for the sequence likelihood (P(X|S)).

**Comment by noxtoby** [comment]
Thanks @csparker and @sea-shunned.

I've implemented an alternative set of changes in [bf65526e8592f3fedb2182fde9c753a1889ad82e](https://github.com/ucl-pond/kde_ebm/commit/bf65526e8592f3fedb2182fde9c753a1889ad82e), where the MM functions are left untouched (plotting too — removing the need for @sea-shunned's requested change), with bespoke new functions added to produce `p(x|E)` and `p(x|~E)` for the EBM, including a snippet for correctly imputing missing data.

Pint for your thoughts.

**Comment by csparker** [comment]
Look good to me Neil. Since you might still want to update ‘pdf()’ while maintaining compatibility with other functions, I’ve added mine too. I’ve tested it a bit with real data and simulations using KDE with fixed controls.

I updated `probability()` back to the original definition, and put `pdf()` into `get_prob_mat()` instead. No changes in the use of `probability()` are now needed.

For plotting, the control_score and patholog_score variables (weighted probabilities p(x|~E) * w_~E and p(x|E)*w_E) were previously from `pdf()`. Since `pdf()` has been updated, I have put the weightings into plotting.py so these variables take the same value as before. 

‘likelihood()’ for mixture model fitting was calling `pdf()` too, so to keep that the same I have put the weightings into the function.

**Comment by noxtoby** [comment]
Thanks again @csparker (for identifying the problem in the first place and contributing a possible fix) and @sea-shunned (for contributing) — I chose instead to use my edits in [PR12](https://github.com/ucl-pond/kde_ebm/pull/12). 

Basically equivalent but subtly different in implementation, plus I did a few extra bits.

**Pull request closed without merging**
